title: yoon's blog
description: 김지윤 기술 블로그
baseurl: "" # the subpath of your site, e.g. /blog
url: "flexton.netlify.com" # the base hostname & protocol for your site, e.g. http://example.com

# Author
author-name:    jiyun
author-image:   1.jpg
author-job:     Web Developer
author-email:   jiyun4251@gmail.com # Add your email for contant form.
# author-twitter: artemsheludko_ # Add your twitter account
about-author:   웹 개발자를 향해 공부하고 있는 김지윤입니다. 공부하고 있는 것을 기록하기 위한 블로그 입니다!

# Social settings
# social-twitter:   artemsheludko_
# social-facebook:
social-github: "https://github.com/jiyun1006"
# social-pinterest: artemsheludko
# social-instagram: artemsheludko_
# social-youtube:
# social-vk:   
# social-linkedin:

# Newsletter
mailchimp: # Add your MailChimp form identifier. For example - blogenjoyfreedom.us16.list-manage.com/subscribe/post?u=cd56155d76ddeeb4c0bc4d080&amp;id=7a526cd13e

# Google Analytics
google-analytics: # Add your identifier. For example UA-99631805-1

# Comment Section (Disqus)
disqus-identifier: mr-brown # Add your shortname for Disqus Comment. For example mr-brown

# Build settings
markdown: kramdown
permalink: /:year/:month/:day/:title/
plugins:
  - jekyll-paginate

paginate: 7
paginate_path: "/page/:num/"

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - vendor
